"""
Shared profile rules — the single source of truth for all adapters.

Each adapter imports ``PROFILE_RULES`` from this module instead of
maintaining its own copy.  Adapter-specific wording or placement
overrides live in the ``adapter_overrides`` dict on each rule.
"""

from __future__ import annotations

from one_context.adapters._rules import AdapterOverride, FieldRule

# ---------------------------------------------------------------------------
# Generated-file marker
# ---------------------------------------------------------------------------

GENERATED_MARKER = "GENERATED by onecxt adapt"

GENERATED_HEADER_MD = (
    f"<!-- {GENERATED_MARKER} — DO NOT EDIT. "
    "Changes will be overwritten. Edit the source in meta/ or knowledge/ instead. -->"
)

GENERATED_NOTICE_JSON = (
    f"{GENERATED_MARKER} — DO NOT EDIT. "
    "Changes will be overwritten. Edit the source in meta/ or knowledge/ instead."
)


def is_generated_content(content: str) -> bool:
    """Return True if *content* contains the generated marker."""
    return GENERATED_MARKER in content


# ---------------------------------------------------------------------------
# Profile rules (13 rules: 8 behavior + 5 output_style)
# ---------------------------------------------------------------------------

PROFILE_RULES: list[FieldRule] = [
    # -- behavior --
    FieldRule(
        "behavior.plan_first", True,
        "Always create a plan and get approval before making changes.",
        section="Behavior",
    ),
    FieldRule(
        "behavior.plan_first", False,
        "You may edit code directly without creating a formal plan first.",
        section="Behavior",
    ),
    FieldRule(
        "behavior.safety_level", "conservative",
        "Take a conservative approach: prefer minimal, reversible changes. "
        "Review each change for unintended side effects.",
        section="Behavior",
    ),
    FieldRule(
        "behavior.safety_level", "standard",
        "Follow standard safety practices when making changes.",
        section="Behavior",
    ),
    FieldRule(
        "behavior.change_scope", "broad",
        "Consider cross-cutting concerns — changes may span multiple files and modules.",
        section="Behavior",
    ),
    FieldRule(
        "behavior.change_scope", "focused",
        "Keep changes focused and scoped to the immediate task.",
        section="Behavior",
    ),
    FieldRule(
        "behavior.test_expectation", "targeted",
        "Write targeted tests for the specific changes you make.",
        section="Behavior",
    ),
    FieldRule(
        "behavior.test_expectation", "advisory",
        "Suggest testing strategies but do not require tests for every change.",
        section="Behavior",
    ),
    # -- output_style --
    FieldRule(
        "output_style.tone", "minimal",
        "Default to minimal output (文言极简 / caveman-style): modern language, "
        "shortest useful phrasing, no filler or pleasantries, do not restate the "
        "user's question—lead with the answer. Unless the user explicitly requests "
        "a different style, length, format, or language, keep replies short.",
        section="Output Style",
        adapter_overrides={
            "claude_code": AdapterOverride(
                output="ALWAYS respond in ≤2 sentences. No filler. "
                "No pleasantries. No restating the question. "
                "Lead with the answer.",
                placement="top",
            ),
            "cursor": AdapterOverride(
                output="Respond in ≤2 lines maximum. No pleasantries. "
                "No restating user input. Lead with the answer.",
                placement="top",
            ),
            "hermes": AdapterOverride(
                output="ALWAYS respond in ≤2 sentences. No filler. "
                "No pleasantries. No restating the question. "
                "Lead with the answer.",
                placement="top",
            ),
        },
    ),
    FieldRule(
        "output_style.tone", "concise",
        "Keep responses concise and to the point.",
        section="Output Style",
    ),
    FieldRule(
        "output_style.tone", "structured",
        "Use structured output with clear headings and sections.",
        section="Output Style",
    ),
    FieldRule(
        "output_style.include_verification", True,
        "Include verification steps (e.g. test commands) after making changes.",
        section="Output Style",
    ),
    FieldRule(
        "output_style.include_verification", False,
        "Verification steps are optional — focus on the design and rationale.",
        section="Output Style",
    ),
]
